### ISSUE TITLE
[Question] Why you decide to switch from Qt to ImGui?

### ISSUE THREAD

**Issue by zettdaymond** [PanosK92/SpartanEngine#13]
Your engine looks awesome! I watched your videos on youtube and your Qt based editor looks great. Why you decide to switch from Qt to ImGui? What is problems you faced with using Qt? (Sorry for bad english)

**Comment by PanosK92** [comment]
Hello Vadim,

A lot of people ask me this question, I guess this is because Qt looks a bit better. 
Here are the main reasons I switched to ImGui:

- MIT licensed, which is one of the most permissive licenses.
- Fast to develop with, I can have a window with some stuff in it, in seconds, literally.
- Easy to maintain, as the logic code and design code are one and the same.
- Platform independence, it can be implemented to run anywhere, which means that after adding Vulkan support, it should be possible to get the engine to run on other platforms.
- Very small, only a few files, Qt is a few GBs and includes a lot of stuff I don't need but can't remove.

As previously mentioned, Qt can look better than ImGui like you mentioned, this is because Qt allowed me to do color gradients, and I was able to make the editor appear more rounded and less flat. 

However, ImGui will introduce color gradients at some point (it's a planned feature), so I will be able to make the enigne very stylish, and I will 😉

Thanks for your interest and your kind words Vadim 👍

**Comment by zettdaymond** [comment]
Thank you for the answer, Panos!

**Comment by erherhh4herh** [comment]
Hey, I didn't know where else to put this, but on the note of ImGui's appearance and functionality, I may have stumbled across something potentially useful: https://github.com/thennequin/ImWindow

It might not help with the gradient thing, but it seems to have lots of compelling features, and its MIT! The only unfortunate thing is that it seems to currently only run on windows. But I hope this helps nonetheless!

**Comment by PanosK92** [comment]
Hi erherhh4herh

No worries, this issue is small and your suggestion is also editor related, so things are clear 👍 
I will write a simple issue template though, in case people with suggestions feel a bit reluctant to reach out.

I can see a node editor that looks nice. I'll take a more in-depth look at this repo during the weekend.
It's also handy to have the link here as the editor will be getting a facelift at some point.

Thanks for keeping me updated!
