### ISSUE TITLE
[Question]Asset Build Pipeline

### ISSUE THREAD

**Issue by OdysseyGameWorks** [PanosK92/SpartanEngine#35]
Spartan is progressing a lot. But one of the most important features I have seen in every game engine is an asset build pipeline. Whenever I would distribute the game made with the engine the game assets like textures, shaders, scripts all need to be built into some custom engine format so that the user can't change them. So how do engines like Unity and Unreal Engine build the assets to a custom engine format so that once distributed the users cannot change shader or textures?

**Comment by PanosK92** [comment]
The custom engine format is usually nothing more than a [binariy](https://en.wikipedia.org/wiki/Binary_file) file, which is something that Spartan does as well.

The primary reason any software uses binary files is because they are fast to read/write, not security.
You could argue that a binary file is not as easy to read as an xml file, which makes things a little bit more secure, but that's a security byproduct, an indirect way to address security, so it's better not to mix the two.

A direct way to address security would be to use some sort of encryption and/or compression.
This will make data slower to read/write by difficult to read.
