### ISSUE TITLE
I love this!  Its only Linux?

### ISSUE THREAD

**Issue by kershnerd** [PanosK92/SpartanEngine#45]
I am sure there are no plans to get this multi-platform, correct?

**Comment by PanosK92** [comment]
Thank you :-)

It currently runs on Windows and there were no plans to get it to run on Linux.

However, the editor is platform agnostic and there is also a Vulkan backend, so I just updated the upcoming features section (in the readme file) with a Linux port. I believe it will open up the engine to more developers who might help further down the line.

Not sure when this will happen though due to time constraints.

**Comment by Calinou** [comment]
This issue can probably be closed in favor of https://github.com/PanosK92/SpartanEngine/issues/66.

**Comment by PanosK92** [comment]
Correct, thanks for spotting this.
