### ISSUE TITLE
Screen space shadows shade triangles of low poly surfaces in a very obvious manner

### ISSUE THREAD

**Issue by PanosK92** [PanosK92/SpartanEngine#81]
A surface being low poly shouldn't matter if the normals are smooth, something wrong is being done in the shader, need to have a look at some point.

**Comment by Nickelium** [comment]
The current algorithm only relies on the Depth buffer and not normal buffers, thus it could be 'works as intended'. I also have noticed similar artefacts in another implementation and Bend's studio implementation aswell. So it depends how obvious these triangulation appears.

If the issue is due to low frequency of the depth buffer, we could tackle with this so called 'high frequency depth bias' that they utilize in Day's gone.

**Comment by PanosK92** [comment]
It might indeed be a natural outcome of the geometry being shaded, haven't looked the Day's Gone slides all that much.

**Comment by PanosK92** [comment]
No longer an issue since we have an entirely new technique for screen space shadows
